### ISSUE TITLE
HackTheBox Sea Çözümü

### ISSUE THREAD

**Issue by Muzaffer188** [skylab-kulubu/article#31]

**Comment by Muzaffer188** [comment]
https://app.hackthebox.com/machines/Sea

MITRE ve OWASP'a göre sızma testi raporu hazırlanması

**Comment by coduronin** [comment]
[HackTheBox Sea Çözümü.pdf](https://github.com/user-attachments/files/17674490/HackTheBox.Sea.Cozumu.pdf)
