### ISSUE TITLE
Shodan ile Dijital İz Raporu

### ISSUE THREAD

**Issue by farukerdem34** [skylab-kulubu/article#33]

**Comment by farukerdem34** [comment]
*istanbul sanayi odası
*yıldız teknik üniversitesi (nur sen kendi üniversiteni yapabilirsin)
*izmir esnaf odaları ve sanat birliği
*pause dergi (hangi şehirde kimler var falan)

**Comment by hacywhatt** [comment]
# Bursa Uludağ Üniversitesi Dijital İz Raporu

Seçtiğim ip `193.140.245.222`
İlk olarak general information kısmını görüyoruz. Host isimleri

- uludag.edu.tr
- uu20.bim.uludag.edu.tr
- isoqlog.uludag.edu.tr
- owmx.uludag.edu.tr
- syslog-ng.uludag.edu.tr
- uu20.uludag.edu.tr
- uu245-222.uludag.edu.tr

Domainler  için; https://www.shodan.io/domain/uludag.edu.tr

![image](https://github.com/user-attachments/assets/6f735d6c-bae5-4f55-a696-b3be6ba39136)

Daha sonra web technologies kısmına bakıyoruz. Shodan  `jQuery 3.2.1 , Select2, Popper ve Bootstrap `kullanıldığını belirledi.

![image](https://github.com/user-attachments/assets/88ce6099-b2a0-4140-8986-00cf55682a84)

Vulnerabilities kısmında bir çok CVE görüyoruz fakat buraya sadece high-level olanları koyacağım.

![image](https://github.com/user-attachments/assets/ed66128d-02b6-4720-b8ef-d988bf43bf76)
![image](https://github.com/user-attachments/assets/b0ff8a72-b1f3-4fdb-841e-1efff8d217ee)
![image](https://github.com/user-attachments/assets/e983ca32-787b-4fae-8933-b300cb6af1c8)
![image](https://github.com/user-attachments/assets/8613400d-b039-48ff-b58e-a5fc20d08e19)

Açık portlar kısmında ` 80, 443 ve 8080 ` portları açık görünüyor. 

![image](https://github.com/user-attachments/assets/63aeea51-1032-40de-b91f-55bd1df98fee)

80 portunda merkez kütüphanemizin kapı geçiş sisteminde Microsoft IIS httpd 8.5 çalışıyor.  4 tanesi low level, 28 tanesi medium level ve 9 tanesi high level güvenlik açığı bulunmakta. 
![image](https://github.com/user-attachments/assets/95a4dd01-82f5-40ac-b063-c9802f991c32)

443 portunda Microsoft HTTPAPI httpd 2.0 çalıştığını görüyoruz.
![image](https://github.com/user-attachments/assets/564d0557-ae5c-473a-819f-3d76418a52f4)

8080 portunda da yine Microsoft HTTPAPI httpd 2.0 çalışmakta.  
![image](https://github.com/user-attachments/assets/e2677b9e-b3d6-4243-a22e-4fc8c84d6c16)
