### ISSUE TITLE
MonitorsThree HackTheBox

### ISSUE THREAD

**Issue by Muzaffer188** [skylab-kulubu/article#34]

**Comment by Muzaffer188** [comment]
https://app.hackthebox.com/machines/MonitorsThree

OWASP ve Mitre Att&ck senaryolarına göre sızma testi raporunun hazırlanması

**Comment by coduronin** [comment]
[MonitorsThree_Write-Up.pdf](https://github.com/user-attachments/files/17995746/MonitorsThree_Write-Up.pdf)
