### ISSUE TITLE
Trickster HackTheBox

### ISSUE THREAD

**Issue by Muzaffer188** [skylab-kulubu/article#37]

**Comment by Muzaffer188** [comment]
https://app.hackthebox.com/machines/Trickster

OWASP ve Mitre Att&ck senaryolarına göre sızma testi raporunun hazırlanması

**Comment by coduronin** [comment]
[Trickster RAPOR.pdf](https://github.com/user-attachments/files/18247367/Trickster.RAPOR.pdf)
